### ISSUE TITLE
Raspberry Pi :: 使用 Raspberry Pi Imager 安装 Ubuntu Server 22.04.1 LTS 时遇到的问题

### ISSUE THREAD

**Issue by dushaoshuai** [dushaoshuai/blog#38]
使用 Raspberry Pi Imager 安装 Ubuntu Server 22.04.1 LTS 时，已经做了如下配置：

![image](https://user-images.githubusercontent.com/56815047/197804144-dff5420b-64eb-463e-a720-cc6b80e1e836.png)

但是使用 `sudo nmap -sn 192.168.0.0/24` 扫描局域网时，仍未找到树莓派的 IP，一开始还以为自己配置有问题，后来在 Ubuntu 官网上找到了[原因](https://ubuntu.com/tutorials/how-to-install-ubuntu-on-your-raspberry-pi#4-boot-ubuntu-server:~:text=your%20Raspberry%20Pi.-,Still,-not%20connected%20to)。

原来 Raspberry Pi Imager 并未正确配置网络，需要手动在 SD 卡上非启动分区上的 `/etc/netplan/` 文件夹下新建 `50-cloud-init.yaml` 文件：

```yaml
wifis:
  wlan0:
    dhcp4: true
    optional: true
    access-points:
      "home network":
        password: "123456789"
```

# See also

[Install Ubuntu on a Raspberry Pi](https://ubuntu.com/download/raspberry-pi)
[How to install Ubuntu Server on your Raspberry Pi](https://ubuntu.com/tutorials/how-to-install-ubuntu-on-your-raspberry-pi#1-overview)
